banknote:
  # http://landon.pw/cdn/1.8_materials.txt
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html - 1.9+
  item: "PAPER"
  name: "&a&lBANK NOTE"
  ################################################################
  # %player% placeholder.
  # Using the default configuration, the lore will look like:
  ################################################################
  # &7Right-click to redeem this &abanknote&7.
  # &7Withdrawn by &a%player&7.
  #
  # &7Value &8» &a&n$%value%
  ################################################################
  lore:
    - "&7Right-click to redeem this &abanknote&7."
    - "&7Withdrawn by &a%player%&7."
  value: "&7Value &8» &a&n$%value%"

options:
  # http://landon.pw/cdn/1.8_sounds.txt
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html - 1.9+
  sound: "SUCCESSFUL_HIT"
  buysound: "CLICK"
  title: "&aWithdraw Menu"
  minimum: 100
  maximum: 9223372036854775807

messages:
  # %value% placeholder.
  redeemed: "&aYou redeemed the Bank Note! &8&l+&a&l&n$%value%"
  purchased: "&aYou withdrew a $%value% Bank Note."
  error: "&cThat is not a number."
  # %difference% placeholder.
  nomoney: "&cNot enough money. You need $%difference% more."

gui:
  # http://landon.pw/cdn/1.8_materials.txt
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html - 1.9+
  first:
    item: "PAPER"
    name: "&b&l$1,000"
    amount: 1
    lore:
      - "&7Left-click to withdraw"
      - "&7a $1,000 Bank Note."
    value: 1000
  second:
    item: "PAPER"
    name: "&b&l$5,000"
    amount: 2
    lore:
      - "&7Left-click to withdraw"
      - "&7a $5,000 Bank Note."
    value: 5000
  third:
    item: "PAPER"
    name: "&b&l$10,000"
    amount: 3
    lore:
      - "&7Left-click to withdraw"
      - "&7a $10,000 Bank Note."
    value: 10000
  custom:
    item: "NAME_TAG"
    name: "&d&l&nCustom Amount"
    amount: 4
    lore:
      - "&7Left-click to withdraw"
      - "&7a custom amount."